### ISSUE TITLE
Changed the og image on the homepage to a different picture, but it still shows up as the old one on facebook... can we make this action effective somehow?

### ISSUE THREAD

**Issue by radiantproject** [victor-rocha/radiant#22]

**Comment by victor-rocha** [comment]
Sorry I didn't reply to your text, I am swamped. So this is a fecebook
issue* (not really an issue, this is who facebook works), so facebook
doesn't update the images they have all the time, the only update them the
first time they see your page. to get them to update your
image/title/content you need to explicitly tell them to do so.

go to:
https://developers.facebook.com/tools/debug/og/object?q=https%3A%2F%2Fwww.theradiantproject.com%2F
enter the URL that you need updated and then click "fetch new information"
then scroll down to see what facebook sees.

151 E. Rosemary St Suite 205
Chapel Hill, NC 27514
Office: 919-951-7929
Cel: 919-903-6708
www.rochapps.com

**Comment by victor-rocha** [comment]
ok something else is happening

151 E. Rosemary St Suite 205
Chapel Hill, NC 27514
Office: 919-951-7929
Cel: 919-903-6708
www.rochapps.com

**Comment by victor-rocha** [comment]
Under the Social Media section there are two og:title fields, the second
one should be og:type and the value should be website (instead of article).
I think by default the value is article, just change it from other pages as
well.

151 E. Rosemary St Suite 205
Chapel Hill, NC 27514
Office: 919-951-7929
Cel: 919-903-6708
www.rochapps.com

**Comment by radiantproject** [comment]
Okay thank you this is fixed!
